version: "3.9"

services:
  postgres:
    container_name: postgres_local
    restart: unless-stopped
    image: postgres:11.13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql